travis:
  secure:
    BINSTAR_TOKEN: xomsaD/XzE8xXFbGjKdrpQDTmjxAoFB5QGli10ryPirv4jVVuL1ZwlGf6XLjY8FPaWZtOcVXY47mBIR20ASE1Cv2lhqHGAA2VLz1/KNZ15k0Ojbxhbxez6+7y/jAkbxjJk7dqiqadJOCVOEVKHRQPZ2iX39vyy3p+Og13r14EfxI6T+aZVkdW7/GpxIM7BLU4cmI3Y+jrrTLUzR5fJ/oqaAxVeu1wlo29z6BCrxroaRyGbnE2lVyZeAwvxKsxaiWHRiP2gaYqA4cS8YQG2NmIQf948NvzUDl2+QBo972t8GuuPpsJe9GkGp9zY06kIFb74MMjp/6h1lZzg1VDKds17fQ6ZKjdHMJ0cFMUXzpkYbiryDygkMKI/tyW02j1/IfTvmZwyFMiGt8bM+diMxa5hpYNzgmEAjSwsRl74nzhIN8QRTtiy3KAp2C5YGqUqGZQzRxliRpvpWCpPhW6Meqme8BDKVxev4d5QVuCFr5MPreHcRYfH3WQWpzF1FcDdPA1IT23fZgWiushf+Cy2Y9ZMDKWH7HbOnoCx3uZpya0T+Q61PFKdQ0Q5NbI2rNVNOwi4Wy9qcfllq11zGBh//g22og8/7Cu9c3/49Gw+Q+T5PVaDmvuxUJinkB8BHPf/ETLgEkT5wefBckf8aLXRZJTRkGUIY7aFIxhALSyKT0VIM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
